language: node_js
node_js:
  - "6"
branches:
  only: master
after_script:
  - cd dist
  - git init
  - git config user.name "Dafrok"
  - git config user.email "o.o@mug.dog"
  - git add .
  - git commit -m "Travis build docs"
  - git push  --force --quiet "https://${GITHUB_TOKEN}@github.com/Dafrok/san-transition.git" master:gh-pages
