language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_script:
  - npm run build
script:
  - npm run lint
  - npm test
  - npm run codecov
  - npm run build:docs
branches:
  only: master
after_script:
  - cd docs/dist
  - git init
  - git config user.name "Dafrok"
  - git config user.email "o.o@mug.dog"
  - git add .
  - git commit -m "Travis build docs"
  - git push  --force --quiet "https://${GITHUB_TOKEN}@github.com/ecomfe/san-transition.git" master:gh-pages
